services:
  server: # Flask App
    build:
      context: .
    command:
      ["gunicorn", "--bind", "0.0.0.0:${CLIENT_PORT}", "main:create_app()"]
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    networks:
      - app-network
    container_name: wedding-server
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/wedding_planner
      - SECRET_KEY=your-secret-key-for-development
      - JWT_SECRET_KEY=your-jwt-secret-key
      - CLIENT_URL=http://localhost:5173

  mongodb: # MongoDB Database
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    name: app-network
    driver: bridge